"""add_memory_relationships

Revision ID: 1218edca5327
Revises: 9cf9d4184551
Create Date: 2026-08-29 06:29:10.591331+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1218edca5327'
down_revision: Union[str, None] = '9cf9d4184551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_relationships',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_memory_id', sa.String(length=64), nullable=False),
    sa.Column('target_memory_id', sa.String(length=64), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_memory_id'], ['memory_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_memory_id'], ['memory_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_relationships_relationship_type'), ['relationship_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_relationships_source_memory_id'), ['source_memory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_relationships_target_memory_id'), ['target_memory_id'], unique=False)
        batch_op.create_index('ix_relationship_src_tgt', ['source_memory_id', 'target_memory_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memory_relationships', schema=None) as batch_op:
        batch_op.drop_index('ix_relationship_src_tgt')
        batch_op.drop_index(batch_op.f('ix_memory_relationships_target_memory_id'))
        batch_op.drop_index(batch_op.f('ix_memory_relationships_source_memory_id'))
        batch_op.drop_index(batch_op.f('ix_memory_relationships_relationship_type'))

    op.drop_table('memory_relationships')
    # ### end Alembic commands ###
