"""deep_upgrade_tenant_and_temporal

Revision ID: 433bb01f2a2a
Revises: 1218edca5327
Create Date: 2026-09-03 11:39:28.730677+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433bb01f2a2a'
down_revision: Union[str, None] = '1218edca5327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deletion_tombstones',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('relational_deleted', sa.Boolean(), nullable=False),
    sa.Column('vector_deleted', sa.Boolean(), nullable=False),
    sa.Column('cache_deleted', sa.Boolean(), nullable=False),
    sa.Column('graph_deleted', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deletion_tombstones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deletion_tombstones_memory_id'), ['memory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deletion_tombstones_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_deletion_tombstones_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_tombstone_tenant_status', ['tenant_id', 'status'], unique=False)

    with op.batch_alter_table('access_grants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=64), nullable=False, server_default='default'))
        batch_op.create_index(batch_op.f('ix_access_grants_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_grant_tenant_agent', ['tenant_id', 'agent_id'], unique=False)

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=64), nullable=False, server_default='default'))
        batch_op.create_index(batch_op.f('ix_agents_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=64), nullable=False, server_default='default'))
        batch_op.create_index(batch_op.f('ix_audit_logs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_audit_tenant_action', ['tenant_id', 'action'], unique=False)

    with op.batch_alter_table('memory_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=64), nullable=False, server_default='default'))
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('entities', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.add_column(sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_memory_records_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_records_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_records_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_memory_tenant_created', ['tenant_id', 'created_at'], unique=False)
        batch_op.create_index('ix_memory_tenant_expires', ['tenant_id', 'expires_at'], unique=False)
        batch_op.create_index('ix_memory_tenant_ns', ['tenant_id', 'namespace_id'], unique=False)
        batch_op.create_index('ix_memory_tenant_owner', ['tenant_id', 'owner_id'], unique=False)
        batch_op.create_index('ix_memory_tenant_state', ['tenant_id', 'lifecycle_state'], unique=False)

    with op.batch_alter_table('namespaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=64), nullable=False, server_default='default'))
        batch_op.create_index(batch_op.f('ix_namespaces_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('namespaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_namespaces_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('memory_records', schema=None) as batch_op:
        batch_op.drop_index('ix_memory_tenant_state')
        batch_op.drop_index('ix_memory_tenant_owner')
        batch_op.drop_index('ix_memory_tenant_ns')
        batch_op.drop_index('ix_memory_tenant_expires')
        batch_op.drop_index('ix_memory_tenant_created')
        batch_op.drop_index(batch_op.f('ix_memory_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_memory_records_expires_at'))
        batch_op.drop_index(batch_op.f('ix_memory_records_content_hash'))
        batch_op.drop_column('expires_at')
        batch_op.drop_column('valid_until')
        batch_op.drop_column('valid_from')
        batch_op.drop_column('observed_at')
        batch_op.drop_column('entities')
        batch_op.drop_column('content_hash')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_tenant_action')
        batch_op.drop_index(batch_op.f('ix_audit_logs_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('access_grants', schema=None) as batch_op:
        batch_op.drop_index('ix_grant_tenant_agent')
        batch_op.drop_index(batch_op.f('ix_access_grants_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('deletion_tombstones', schema=None) as batch_op:
        batch_op.drop_index('ix_tombstone_tenant_status')
        batch_op.drop_index(batch_op.f('ix_deletion_tombstones_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_deletion_tombstones_status'))
        batch_op.drop_index(batch_op.f('ix_deletion_tombstones_memory_id'))

    op.drop_table('deletion_tombstones')
    # ### end Alembic commands ###
