"""create_memora_tables

Revision ID: 8a8f529e1cdb
Revises: 
Create Date: 2026-08-29 06:14:41.080087+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a8f529e1cdb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_name'), ['name'], unique=True)

    op.create_table('namespaces',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('type', sa.Enum('agent-private', 'project-private', 'team-shared', 'universe-global', 'public', name='namespacetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('namespaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_namespaces_path'), ['path'], unique=True)
        batch_op.create_index(batch_op.f('ix_namespaces_type'), ['type'], unique=False)

    op.create_table('memory_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('namespace_id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('memory_type', sa.Enum('episodic', 'semantic', 'procedural', 'preference', 'working', 'decision', 'relationship', 'experience', 'project', 'tool', 'system', name='memorytype'), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('lifecycle_state', sa.Enum('candidate', 'active', 'verified', 'superseded', 'archived', 'deleted', name='lifecyclestate'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['memory_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_records', schema=None) as batch_op:
        batch_op.create_index('ix_memory_ns_state', ['namespace_id', 'lifecycle_state'], unique=False)
        batch_op.create_index('ix_memory_owner_type', ['owner_id', 'memory_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_records_lifecycle_state'), ['lifecycle_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_records_memory_type'), ['memory_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_records_namespace_id'), ['namespace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_records_owner_id'), ['owner_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('memory_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['memory_id'], ['memory_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_memory_id'), ['memory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_memory_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('memory_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_records_owner_id'))
        batch_op.drop_index(batch_op.f('ix_memory_records_namespace_id'))
        batch_op.drop_index(batch_op.f('ix_memory_records_memory_type'))
        batch_op.drop_index(batch_op.f('ix_memory_records_lifecycle_state'))
        batch_op.drop_index(batch_op.f('ix_memory_records_created_at'))
        batch_op.drop_index('ix_memory_owner_type')
        batch_op.drop_index('ix_memory_ns_state')

    op.drop_table('memory_records')
    with op.batch_alter_table('namespaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_namespaces_type'))
        batch_op.drop_index(batch_op.f('ix_namespaces_path'))

    op.drop_table('namespaces')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_name'))

    op.drop_table('agents')
    # ### end Alembic commands ###
