"""add_subagents_and_access_grants

Revision ID: 9cf9d4184551
Revises: 8a8f529e1cdb
Create Date: 2026-08-29 06:19:36.341815+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf9d4184551'
down_revision: Union[str, None] = '8a8f529e1cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_grants',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('agent_id', sa.String(length=64), nullable=False),
        sa.Column('namespace_id', sa.String(length=64), nullable=False),
        sa.Column('actions', sa.JSON(), nullable=False),
        sa.Column('purpose', sa.String(length=256), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['namespace_id'], ['namespaces.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_grants_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_grants_namespace_id'), ['namespace_id'], unique=False)
        batch_op.create_index('ix_grant_agent_ns', ['agent_id', 'namespace_id'], unique=False)

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=64), nullable=False, server_default='worker'))
        batch_op.add_column(sa.Column('parent_agent_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('bounded_scope', sa.String(length=256), nullable=True))
        batch_op.create_foreign_key('fk_agents_parent_agent_id', 'agents', ['parent_agent_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_agents_parent_agent_id', type_='foreignkey')
        batch_op.drop_column('bounded_scope')
        batch_op.drop_column('parent_agent_id')
        batch_op.drop_column('role')

    with op.batch_alter_table('access_grants', schema=None) as batch_op:
        batch_op.drop_index('ix_grant_agent_ns')
        batch_op.drop_index(batch_op.f('ix_access_grants_namespace_id'))
        batch_op.drop_index(batch_op.f('ix_access_grants_agent_id'))

    op.drop_table('access_grants')
    # ### end Alembic commands ###
